# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Print directory structure
      run: ls -R

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential
        sudo apt-get install -y libwayland-dev
        sudo apt-get install -y libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev
        sudo apt-get install -y libglfw3-dev libxkbcommon-dev
        sudo apt-get install -y libgl1-mesa-dev libglu1-mesa-dev

    - name: Create build directory
      run: mkdir build

    - name: Navigate to build directory and run CMake
      run: |
        cd build
        cmake ..
        cmake --build .

    ##- name: Run the executable
    ##  run: ./bin/AbstractCity
