name: CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Print directory structure
      run: ls -R

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential
        sudo apt-get install -y libwayland-dev libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev
        sudo apt-get install -y libglfw3-dev libxkbcommon-dev
        sudo apt-get install -y libgl1-mesa-dev libglu1-mesa-dev
        sudo apt-get install -y xvfb  # Install Xvfb for virtual display

    - name: Create build directory
      run: mkdir build

    - name: Configure and Build
      run: |
        cd build
        cmake ..
        cmake --build .

    - name: Run the executable with Xvfb
      run: |
        xvfb-run ./build/bin/AbstractCity

